plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/jasminestock/Documents/JDesigns/JDesigns-Website"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/brain-guide"
to = "/systemize-your-business"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/brain-guide.html"
to = "/systemize-your-business"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/command-pack"
to = "/systemized"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/command-pack.html"
to = "/systemized"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/business-brain-command-pack/*"
to = "/systemized"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]